// Generated from validated data/history indexes.
// Do not edit this file directly.

export type SubjectHistoryFieldChange = {
  readonly field: string;
  readonly before: string;
  readonly after: string;
};

export type SubjectHistoryChange = {
  readonly type: 'added' | 'removed' | 'changed';
  readonly lectureCode: string;
  readonly titleBefore: string | null;
  readonly titleAfter: string | null;
  readonly fields: readonly SubjectHistoryFieldChange[];
};

export type SubjectHistoryEntry = {
  readonly academicYear: string;
  readonly baseRetrievedAt: string;
  readonly targetRetrievedAt: string;
  readonly baseSubjectCount: number;
  readonly targetSubjectCount: number;
  readonly addedCount: number;
  readonly removedCount: number;
  readonly changedCount: number;
  readonly changes: readonly SubjectHistoryChange[];
};

export const subjectHistory: readonly SubjectHistoryEntry[] = [];
