// Generated from data/subjectDataManifest.json
// Do not edit this file directly.

import { rawSubjectProperties } from '../types/rawSubjectProperties';
import type { RawSubjectMap } from '../types/subject';

export const subjectDataManifest = {
  dataFile: 'subject_details_main_2026-08-16_6a424cab5342.json',
  academicYear: '2026年度',
  retrievedAt: '2026-08-16',
  subjectCount: 12481,
  source: 'https://momiji.hiroshima-u.ac.jp/syllabusHtml/',
  schemaVersion: 1,
  structureReport: {
    dataFile:
      'subject_structure_subject_details_main_2026-08-16_6a424cab5342_af08d8f17f76.json',
    sha256: 'af08d8f17f76773c45d52a84615e1eaa90d3d1349db86611f011d67afb4a56bd',
  },
} as const;

export const subjectDataUrl = new URL(
  '../../data/subject_details_main_2026-08-16_6a424cab5342.json',
  import.meta.url
).href;

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return (
    value !== null &&
    typeof value === 'object' &&
    Object.getPrototypeOf(value) === Object.prototype
  );
}

export function validateRawSubjectMap(
  value: unknown
): asserts value is RawSubjectMap {
  if (!isPlainObject(value)) {
    throw new Error('Subject data must be a plain object.');
  }
  if (Object.keys(value).length !== subjectDataManifest.subjectCount) {
    throw new Error('Subject data count does not match the active manifest.');
  }

  for (const [subjectCode, subject] of Object.entries(value)) {
    if (!isPlainObject(subject)) {
      throw new Error('Subject ' + subjectCode + ' must be a plain object.');
    }
    const subjectKeys = Object.keys(subject);
    const missingProperty = rawSubjectProperties.find(
      (property) => !Object.hasOwn(subject, property)
    );
    if (missingProperty) {
      throw new Error(
        'Subject ' + subjectCode + ' is missing field: ' + missingProperty + '.'
      );
    }
    const unexpectedProperty = subjectKeys.find(
      (property) =>
        !rawSubjectProperties.some(
          (knownProperty) => knownProperty === property
        )
    );
    if (
      unexpectedProperty ||
      subjectKeys.length !== rawSubjectProperties.length
    ) {
      throw new Error('Subject ' + subjectCode + ' has an unexpected field.');
    }
    for (const property of rawSubjectProperties) {
      if (typeof subject[property] !== 'string') {
        throw new Error(
          'Subject ' + subjectCode + ' field ' + property + ' must be a string.'
        );
      }
    }
    if (subject['講義コード'] !== subjectCode) {
      throw new Error(
        'Subject ' + subjectCode + ' has a mismatched 講義コード.'
      );
    }
    if (subject['年度'] !== subjectDataManifest.academicYear) {
      throw new Error('Subject ' + subjectCode + ' has a mismatched 年度.');
    }
  }
}

export async function loadSubjectData(
  cache: RequestCache = 'default'
): Promise<RawSubjectMap> {
  const response = await fetch(subjectDataUrl, { cache });
  if (!response.ok) {
    throw new Error(
      'Subject data request failed: HTTP ' +
        response.status +
        ' ' +
        response.statusText
    );
  }

  let data: unknown;
  try {
    data = await response.json();
  } catch (error) {
    throw new Error('Subject data response was not valid JSON.', {
      cause: error,
    });
  }
  validateRawSubjectMap(data);
  return data;
}
