// Generated from data/subjectDataManifest.json
// Do not edit this file directly.

import subjectData from '../../data/subject_details_main_2026-04-07.json';

export { subjectData };
export const subjectDataManifest = {
  dataFile: 'subject_details_main_2026-04-07.json',
  academicYear: '2026年度',
  retrievedAt: '2026-04-07',
  subjectCount: 12489,
  source: 'https://momiji.hiroshima-u.ac.jp/syllabusHtml/',
} as const;
